---
- name: Test playbook that only tests the dependencies are working
  hosts: localhost

  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: "Hello world"

    - name: Test ansible vault decryption
      ansible.builtin.assert:
        that:
          - test_vault_secret == 'SuperSecret'
