---
name: Test python and ansible

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get ansible executable
        run: command -v ansible
      - name: Get directory information
        run: |
          echo $HOME
          pwd
      - name: Generate SSH key
        run: ssh-keygen -t ed25519 -f "${HOME}/.ssh/id_ed25519" -q -P ""
      - uses: tanmancan/action-setup-ssh-agent-key@1.0.0
      - name: Add key
        run: ssh-add
      - name: Store ansible-vault key to keyring
        run: keyring set ansible-vault key < <(echo '123456')
      - name: Run test ansible playbook
        run: ansible-playbook pb_test.yml
